### ISSUE TITLE
The new design breaks the simple premise of the tool

### ISSUE THREAD

**Issue by ringofyre** [az0/linkgopher#70]
which is to be able to copy links as texts.

Sorry - this is a tool I've used for years and now it's literally useless.

**Comment by az0** [comment]
On Mozilla, I disabled Link Gopher version 2.6.1, which makes version 2.5.0 the primary version. I assume it will not downgrade you, so you may need to reinstall. Let me know how it goes.

**Comment by rvbtnks** [comment]
> which is to be able to copy links as texts.
> 
> Sorry - this is a tool I've used for years and now it's literally useless.

i'm sure the intent was well, but yeah...the extension worked perfect for what i needed before.

**Comment by ringofyre** [comment]
> On Mozilla, I disabled Link Gopher version 2.6.1, which makes version 2.5.0 the primary version. I assume it will not downgrade you, so you may need to reinstall. Let me know how it goes.

Thank you - I've dld the 2.50 xpi from Mozilla "Previous Ver.", removed 2.61 and disabled automatic updates.

I think a fresh look is great and the design was not unattractive but don't fuck with the formatting - for those of us on os's that a strict on line breaks etc. (linux, commandline) adding a space between lines is just extra steps.

**Comment by mharris1319** [comment]
Respectfully, +1.  Grateful for this extension but really, really disliked the new design.  Keep it as is.

**Comment by az0** [comment]
@mharris1319 Were you able to find your way back to version 2.5.0?

**Comment by mharris1319** [comment]
Yes, thank you, afterwards I left that comment.

**Comment by Labryn** [comment]
> > On Mozilla, I disabled Link Gopher version 2.6.1, which makes version 2.5.0 the primary version. I assume it will not downgrade you, so you may need to reinstall. Let me know how it goes.
> 
> Thank you - I've dld the 2.50 xpi from Mozilla "Previous Ver.", removed 2.61 and disabled automatic updates. & can confirm that it works.
> 
> I think a fresh look is great and the design was not unattractive but don't fuck with the formatting

 - for those of us on os's that a strict on line breaks etc. (linux, commandline) adding a space between lines is just extra steps.

I deeply apologize. I designed the layout, and I messed up big time by not considering how other's beyond myself were using it, especially with other OS's, as you pointed out, that all slipped my mind, and I'm extremely sorry for messing up. I just want to make sure that you know that the fault lies with me, and not with @az0, and again I apologize.

**Comment by az0** [comment]
Next time I will test these cases more carefully.

**Comment by mharris1319** [comment]
I hope you do not mind me reopening this just to say to @az0 and to @Labryn: you are very much appreciated.  Your work is very much appreciated.  

@az0, this is a fantastic extension that I find myself using daily to efficiently pull links from certain pages that otherwise don't permit it (TikTok favorites, Reddit saves, etc.).   Do you have a Ko-Fi or something?  For the amount of use I give this thing I should at least buy you the Ko-Fi equivalent of a pizza or something.

And @Labryn, I have had ideas before that I thought were wonderful and efficient and great, and when they hit the light of day with other people, I got my a** handed back to me, so that sort of experience of misalignment is by no means unique to you.  UI is always a learning experience and a changing target and even huge companies get it completely wrong sometime.

I just frankly don't want either of you to walk away feeling bad about this.  This is a great extension -- and @Labryn even if this particular redesign didn't work, you wanted to make something better, and that's an admirable motivation.

**Comment by Labryn** [comment]
> I hope you do not mind me reopening this just to say to @az0 and to @Labryn: you are very much appreciated.  Your work is very much appreciated.  
> 
> @az0, this is a fantastic extension that I find myself using daily to efficiently pull links from certain pages that otherwise don't permit it (TikTok favorites, Reddit saves, etc.).   Do you have a Ko-Fi or something?  For the amount of use I give this thing I should at least buy you the Ko-Fi equivalent of a pizza or something.
> 
> And @Labryn, I have had ideas before that I thought were wonderful and efficient and great, and when they hit the light of day with other people, I got my a** handed back to me, so that sort of experience of misalignment is by no means unique to you.  UI is always a learning experience and a changing target and even huge companies get it completely wrong sometime.
> 
> I just frankly don't want either of you to walk away feeling bad about this.  This is a great extension -- and @Labryn even if this particular redesign didn't work, you wanted to contribute towards making something better, and that's an admirable motivation.

Thank you so much! @az0 should take all the credit. He's the genius behind the extension. I actually was just going to do a dark mode for myself, but @az0 is a good guy and was thinking about the whole picture, his extension, and everyone who uses it, and I am tell he just wants whoever uses Link Gopher to be satisfied. I had a few ideas like
